-- Run this query in your Supabase SQL Editor to create the contacts table

create table contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  phone text not null,
  email text not null,
  message text,
  status text default 'new' -- 'new', 'contacted', 'closed'
);

-- Enable Row Level Security (RLS) is generally recommended, 
-- but for a simple public contact form where anyone can insert, 
-- you can either keep RLS off or set a policy to allow public inserts.

-- Enable Row Level Security (RLS)
alter table contacts enable row level security;

-- Policy 1: Allow anyone (anon) to INSERT data (So the contact form works)
create policy "Allow public inserts" 
on contacts for insert 
with check (true);

-- Policy 2: Allow authenticated users (Admin) to SELECT data (View the dashboard)
create policy "Allow internal read access" 
on contacts for select 
using (auth.role() = 'authenticated');
