-- Run this query in your Supabase SQL Editor to create the contacts table

create table contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  phone text not null,
  email text not null,
  message text,
  status text default 'new' -- 'new', 'contacted', 'closed'
);

-- Enable Row Level Security (RLS) is generally recommended, 
-- but for a simple public contact form where anyone can insert, 
-- you can either keep RLS off or set a policy to allow public inserts.

-- Enable Row Level Security (RLS)
alter table contacts enable row level security;

-- Policy 1: Allow anyone (anon) to INSERT data (So the contact form works)
create policy "Allow public inserts" 
on contacts for insert 
with check (true);

-- Policy 2: Allow authenticated users (Admin) to SELECT data (View the dashboard)
create policy "Allow internal read access" 
on contacts for select 
using (auth.role() = 'authenticated');

-- PROFILES TABLE (For Role-Based Access Control)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  role text default 'user' check (role in ('user', 'admin')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for profiles
alter table profiles enable row level security;

-- Policy: Users can read their own profile
create policy "Users can view own profile" on profiles 
for select using (auth.uid() = id);

-- TRIGGER: Automatically create profile on signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'user');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- UPDATE CONTACTS POLICY TO USE ROLES
drop policy "Allow internal read access" on contacts;

create policy "Admins can view all contacts" 
on contacts for select 
using (
  exists (
    select 1 from profiles
    where profiles.id = auth.uid()
    and profiles.role = 'admin'
  )
);

-- APPOINTMENTS TABLE
create table public.appointments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  appointment_date date not null,
  appointment_time time not null,
  reason text,
  status text default 'pending' -- 'pending', 'confirmed', 'completed', 'cancelled'
);

-- Enable RLS for appointments
alter table appointments enable row level security;

-- Policy 1: Users can INSERT their own appointments
create policy "Users can insert own appointments" 
on appointments for insert 
with check (auth.uid() = user_id);

-- Policy 2: Users can VIEW their own appointments
create policy "Users can view own appointments" 
on appointments for select 
using (auth.uid() = user_id);

-- Policy 3: Admins can VIEW ALL appointments
create policy "Admins can view all appointments" 
on appointments for select 
using (
  exists (
    select 1 from profiles
    where profiles.id = auth.uid()
    and profiles.role = 'admin'
  )
);
