-- Run this query in your Supabase SQL Editor to create the contacts table

create table contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  phone text not null,
  email text not null,
  message text,
  status text default 'new' -- 'new', 'contacted', 'closed'
);

-- Enable Row Level Security (RLS) is generally recommended, 
-- but for a simple public contact form where anyone can insert, 
-- you can either keep RLS off or set a policy to allow public inserts.

-- Option 1: Disable RLS (Simpler for getting started)
alter table contacts disable row level security;

-- Option 2: Allow public inserts (More secure)
-- alter table contacts enable row level security;
-- create policy "Allow public inserts" on contacts for insert with check (true);
-- create policy "Allow read access for authenticated users only" on contacts for select using (auth.role() = 'authenticated');
